### ISSUE TITLE
Trying to stream and log GSR data through Shimmer3 sensors in Windows leads to a ValueError

### ISSUE THREAD

**Issue by SrikrishnaBhat** [octopus-sensing/octopus-sensing#61]
Getting the following error when trying to monitor through the GSR sensor on windows:
```
Traceback (most recent call last):
  File "D:\test_octopus_project\shimmer_sensor.py", line 46, in <module>
    add_sensors_and_stream()
  File "D:\test_octopus_project\shimmer_sensor.py", line 27, in add_sensors_and_stream
    device_coordinator.add_devices([my_shimmer])
  File "D:\Python\Miniconda3\lib\site-packages\octopus_sensing\device_coordinator.py", line 144, in add_devices
    self.add_device(device)
  File "D:\Python\Miniconda3\lib\site-packages\octopus_sensing\device_coordinator.py", line 122, in add_device
    device.start()
  File "D:\Python\Miniconda3\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\Python\Miniconda3\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Python\Miniconda3\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "D:\Python\Miniconda3\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Python\Miniconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
ValueError: ctypes objects containing pointers cannot be pickled

(base) D:\test_octopus_project>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Python\Miniconda3\lib\multiprocessing\spawn.py", line 107, in spawn_main
    new_handle = reduction.duplicate(pipe_handle,
  File "D:\Python\Miniconda3\lib\multiprocessing\reduction.py", line 79, in duplicate
    return _winapi.DuplicateHandle(
PermissionError: [WinError 5] Access is denied
```
It seems the following stackoverflow link suggests switching to a multi-threading model instead: https://stackoverflow.com/a/57738817. I know switching to that will be quite a bit of effort, want to know if there is something else that I am missing here.

**Comment by aidin36** [comment]
Thanks for reporting this.

I did a change that hopefully will fix this issue.
We don't own a Windows machine, so we can't actually re-produce and check your issue. Can you please test if my commit solved your issue?

No version is released with this change yet, so you need to install it directly from the Github repo. For example, if you use `pipenv`:

```
pipenv install git+https://github.com/octopus-sensing/octopus-sensing#egg=octopus-sensing
```
(You might need to remove the previous version.)

Also, can you please tell me a little more about your environment setup? Python version, what version of Windows, is it Window's command-prompt or something like MSYS2, are you using Pipenv?

**Comment by aidin36** [comment]
Also, I added a parameter for `serial_port` in the above commit. Documents updated as well.

**Comment by SrikrishnaBhat** [comment]
@aidin36 Sure, will take a look and get back.

**Comment by SrikrishnaBhat** [comment]
@aidin36 Is this the only file that you changed: https://github.com/octopus-sensing/octopus-sensing/commit/08578935a6725a97c373c881ea53b10dcc157fb6? I will test it, but from what I see, I think, this addresses the following issue: https://github.com/octopus-sensing/octopus-sensing/issues/62 which is about providing option for users to use the serial port of their choosing.

**Comment by SrikrishnaBhat** [comment]
@aidin36 nvm, that worked. So what was the problem? I am guessing since I manually customised the Com Port to be used by Windows, that was causing a permission issue?

**Comment by aidin36** [comment]
Thanks for testing!
If you look closely at the change, I moved the initialisation part to the `_run` method, which will be run inside the child process. That resolved the multiprocess issue.

**Comment by SrikrishnaBhat** [comment]
Ah, that explains it. Thanks for looking into it!
